export default function Head() {
  return (
    <>
      <title>Max Randle</title>
      <meta name="description" content="Generated by create next app" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
      ></meta>
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
