import "@/styles/tailwind.css";
import "@/styles/color-spectrum.scss";
import "@/styles/theme.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <body className="min-h-screen overflow-hidden pb-20">{children}</body> */}
      <body>
        <div className="min-h-screen overflow-hidden pb-20">{children}</div>
      </body>
    </html>
  );
}
