"use client";

import "@/styles/tailwind.scss";
import "@/styles/color-spectrum.scss";
import "@/styles/base-theme.scss";

import { ThemeProvider, useTheme } from "@/hooks/useTheme";
import { twMerge } from "tailwind-merge";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const RootLayoutInner: React.FC<{ children: React.ReactNode }> = ({
  children,
}: {
  children: React.ReactNode;
}) => {
  const { theme } = useTheme();

  return (
    <html lang="en">
      <body>
        <div className="min-h-screen overflow-hidden pb-20">{children}</div>
      </body>
    </html>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // <ThemeProvider>
    //   <RootLayoutInner>{children}</RootLayoutInner>
    // </ThemeProvider>

    <html lang="en">
      <body>
        <div className="min-h-screen overflow-hidden">{children}</div>
      </body>
    </html>
  );
}
